### ISSUE TITLE
"arduino multi ISP" breaks arduinoISP

### ISSUE THREAD

**Issue by WestfW** [facchinm/avrdude#1]
This patch
https://github.com/facchinm/avrdude/commit/3038a3bce9a05e27e3d876edc454ab835c489b9b#diff-53fea9d6d8c455cf68a521363ffacf2c

Adds additional parameters to the STK500 initialization, which breaks existing versions of the ArduinoISP sketch which isn't expecting them.  It is dependent on SWMIN version number reported by the programmer, but it checks against the OLD ArduinoISP version (18) instead of using a new version.  (grr.)

See https://github.com/arduino/avrdude-build-script/issues/11

**Comment by facchinm** [comment]
Fixed by reverting 3038a3b and published avrdude-6.3.0-arduino14 (core 1.6.207)
