### ISSUE TITLE
Incorrect device signatures

### ISSUE THREAD

**Issue by MCUdude** [facchinm/avrdude#5]
It seems like some signatures are wrong. I haven't checked every new ATtiny yet, but this is a start:

|            | Signature in avrdude.conf  | Correct signature |
|------------|----------------------------|-------------------|
| ATmega3209 | 0x1E 0x95 0x53             | 0x1E 0x95 0x31    |
| ATmega3208 | 0x1E 0x95 0x52             | 0x1E 0x95 0x30    |
| ATtiny402  | 0x1E 0x92 0x23             | 0x1E 0x92 0x27    |

**Comment by facchinm** [comment]
@MCUdude has this already been reported upstream?
I'd prefer not to add too many out of tree patches :wink:

**Comment by MCUdude** [comment]
I have no idea where to report it. This is the only place I've reported it.

**Comment by per1234** [comment]
Here's the official AVRDUDE bug tracker:
https://savannah.nongnu.org/bugs/?group=avrdude

I just did a search there for ATmega3209, ATmega3208, and ATtiny402 and got no results. I also did a search for "signature" and found no relevant results.

**Comment by per1234** [comment]
I forgot to say that I also did the same searches in the [patches](https://savannah.nongnu.org/patch/?group=avrdude).

**Comment by MCUdude** [comment]
Looks like this issue was fixed in #11
