### ISSUE TITLE
328pb efuse has a bit 3 for clock failure detection

### ISSUE THREAD

**Issue by epccs** [facchinm/avrdude#6]
for reference see:

https://github.com/epccs/avrdude/commit/ffd1745607c1b0e63f4ea44b219f786d99aae185

**Comment by facchinm** [comment]
Hi @epccs ,
would you mind posting this patch in official avrdude (http://savannah.nongnu.org/projects/avrdude)? This repo is intended as much as possible as a mirror or the official one, just translated into git format from svn.

**Comment by epccs** [comment]
I understand I will try to figure out how to do that.
